version: "3"

services:

  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data            # default
      POSTGRES_INITDB_ARGS: "--data-checksums"    # default