spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: user
    password: password
  jpa.hibernate.ddl-auto: create-drop


# Workaround for https://hibernate.atlassian.net/browse/HHH-12368:
# Increase log level
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR