spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
#       ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Workaround for https://hibernate.atlassian.net/browse/HHH-12368:
# Increase log level
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR